from typing import Protocol

from ..models.stream import StreamConfig


class StreamingPlatform(Protocol):
    def authenticate(self) -> None: ...

    def create_stream(self, config: StreamConfig) -> None: ...

    def end_stream(self) -> None: ...


class OBSController(Protocol):
    def connect(self) -> None: ...

    def disconnect(self) -> None: ...

    def configure_primary_output(self, server: str, key: str) -> None: ...

    def configure_secondary_output(self, name: str, server: str, key: str) -> None: ...

    def start_streaming(self) -> None: ...

    def stop_streaming(self) -> None: ...

    def start_output(self, name: str) -> None: ...

    def stop_output(self, name: str) -> None: ...
